### ISSUE TITLE
UIWebView reference still exists in v1.0.1

### ISSUE THREAD

**Issue by SMFakhir** [Tealium/tealium-xamarin#4]
Hi, All the references were removed in v5.6.0 of iOS SDK

This Xamarin version encapsulates v5.6.5 of iOS and still, I could find the trace of UIWebView in the binary.

The following command can be run to find the trace.
`grep -r "UIWebView" .`

**Comment by jonathanswong** [comment]
Hi @SMFakhir . Thanks for bringing this to our attention. We'll get back to you as soon as we can make the necessary updates. Thanks.

**Comment by SMFakhir** [comment]
Is there any workaround for now? If I can convert the iOS frameworks to DLLs, do you think it would work?

**Comment by jonathanswong** [comment]
Hi @SMFakhir . I think the workaround would be to fork the repo and update it to use the public-facing [tealium-swift](https://github.com//tealium/tealium-swift) library instead of the older close-sourced TealiumIOS library. That being said, it would take some work on your end and it would probably be easier to wait for us to update this repo with the right TealiumIOS version. 

We'll try to get this fixed for you ASAP.

**Comment by SMFakhir** [comment]
Hi, Thanks!

Its been 3 days, Is it possible for you to estimate this so i can plan my work accordingly. Thanks.

**Comment by jonathanwong** [comment]
Hi @SMFakhir . This is hopefully something we can tackle later this week or early next. Sorry for the delay.

**Comment by jonathanswong** [comment]
Hi @SMFakhir . This is hopefully something we can tackle later this week or early next. Sorry for the delay.

**Comment by SMFakhir** [comment]
Hi, would like to ask if you guys have any update on this? we have a release scheduled for end of this week so i'd appreciate if you guys can expedite this fix.

**Comment by craigrouse** [comment]
@SMFakhir I can't make any guarantees, but we're working on this right now and will do our best to get it released ASAP. We'll keep you updated.

**Comment by craigrouse** [comment]
@SMFakhir Version 1.0.2 is now live and has the updated core libraries. The package is also available on [Nuget](https://www.nuget.org/packages/Tealium.Xamarin/).

**Comment by SMFakhir** [comment]
Thanks

**Comment by SMFakhir** [comment]
Hi, I'm still getting a reference in Tealium.Platform.iOS.dll
<img width="569" alt="image" src="https://user-images.githubusercontent.com/7599643/95602134-ea16ae00-0a6d-11eb-81b5-5973e3dcd24f.png">

**Comment by craigrouse** [comment]
@SMFakhir you will get this due to the dSYM file still containing a reference to UIKit, which contains UIWebView references, but it shouldn't prevent you from submitting to Apple. Please try and come back to us if your app is rejected.

**Comment by SMFakhir** [comment]
Sure, thanks
